'use strict'

// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'development'
process.env.NODE_ENV = 'development'

// Makes the script crash on unhandled rejections instead of silently
// ignoring them. In the future, promise rejections that are not handled will
// terminate the Node.js process with a non-zero exit code.
process.on('unhandledRejection', (err) => {
    throw err
})

// Ensure environment variables are read.
require('../config/env')

const fs = require('fs')
const chalk = require('chalk')
const webpack = require('webpack')
const WebpackDevServer = require('webpack-dev-server')
const paths = require('../config/paths')
const configFactory = require('../config/webpack.config')
const createDevServerConfig = require('../config/webpackDevServer.config')
const {
    formatWebpackMessages,
    checkBrowsers,
} = require('../config/build-utils')

const isInteractive = process.stdout.isTTY

// Warn and crash if required files are missing
if (!fs.existsSync(paths.appHtml) || !fs.existsSync(paths.appIndexJs)) {
    console.log(chalk.red('Could not find one of the required files:'))
    console.log(chalk.red('  ' + paths.appHtml))
    console.log(chalk.red('  ' + paths.appIndexJs))
    process.exit(1)
}

// Tools like Cloud9 rely on this.
const DEFAULT_PORT = parseInt(process.env.PORT, 10) || 8500
const HOST = process.env.HOST || '0.0.0.0'

if (process.env.HOST) {
    console.log(
        chalk.cyan(
            `Attempting to bind to HOST environment variable: ${chalk.yellow(
                chalk.bold(process.env.HOST)
            )}`
        )
    )
    console.log(
        `If this was unintentional, check that you haven't mistakenly set it in your shell.`
    )
    console.log(`Learn more here: ${chalk.yellow('https://bit.ly/CRA-advanced-config')}`)
    console.log()
}

// We require that you explicitly set browsers and do not fall back to
// browserslist defaults.
const port = DEFAULT_PORT
checkBrowsers(paths.appPath, isInteractive)
    .then(() => {
        const config = configFactory('development')
        const protocol = process.env.HTTPS === 'true' ? 'https' : 'http'

        // Create a webpack compiler with custom message formatting
        const compiler = webpack(config)
        compiler.hooks.done.tap('atlas-dev', (stats) => {
            const jsonStats = stats.toJson({ all: false, warnings: true, errors: true })
            const messages = formatWebpackMessages(jsonStats)
            if (messages.errors.length) {
                console.log(chalk.red('Failed to compile.\n'))
                console.log(messages.errors.join('\n\n'))
                return
            }
            if (messages.warnings.length) {
                console.log(chalk.yellow('Compiled with warnings.\n'))
                console.log(messages.warnings.join('\n\n'))
            } else {
                console.log(chalk.green('Compiled successfully!\n'))
            }
        })

        // Load proxy config
        const proxySetting = require(paths.appPackageJson).proxy
        // Serve webpack assets generated by the compiler over a web server.
        const serverConfig = createDevServerConfig(proxySetting, HOST)
        const devServer = new WebpackDevServer(serverConfig, compiler)
        // Launch WebpackDevServer.
        devServer.startCallback((err) => {
            if (err) {
                return console.log(err)
            }
            if (isInteractive) {
                console.clear()
            }

            console.log(chalk.cyan(`Development server listening on localhost:${port}\n`))
        })
        ;['SIGINT', 'SIGTERM'].forEach(function (sig) {
            process.on(sig, function () {
                devServer.stop()
                process.exit()
            })
        })
    })
    .catch((err) => {
        if (err && err.message) {
            console.log(err.message)
        }
        process.exit(1)
    })
